### PR TITLE
Added Xdebug installation and basic ini configuration to each Dockerfile

### PR DESCRIPTION
**Pull request by Persata**

### CODE REVIEW

**Comment by chrisshennan** [comment]
Hi,

Rather than doing these changes directly into master I was considering the approach of having the normal image held in i.e. `7/fpm/Dockerfile` and we add a new dev version i.e. `7/fpm/dev/Dockerfile`  This would allow us to use the normal image in prod / occasions where we are not using xdebug but could still make use of the `-dev` version when we are using xdebug.

Thoughts?

Chris.

**Comment by Persata** [comment]
Hi,

I think that's a good idea - definitely don't want the performance penalty on live / whenever we're load testing the setup / etc that comes with having Xdebug enabled. Two separate images means it'll be easy to swap between them.

Do you think it's worth using

```
FROM thedrum/php:7-fpm
```

in the dev Dockerfile with a single additional step for Xdebug, or should we replicate the whole base Dockerfile?

-- Ross.

**Comment by chrisshennan** [comment]
Hi,

If you use the 

```
FROM thedrum/php:7-fpm
```

then if we make changes to the base image they will propagate through to the dev image automatically.

Many thanks.

Chris.

**Comment by Persata** [comment]
Hi,

I've added 3 new dev Dockerfiles that add Xdebug on top of the base images.

-- Ross.

**Pull request merged**
